version: '3.4'

services:
  billingservice:
    image: billingservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: development
    ports:
      - 202:202
      - 9229:9229
    command: ["node", "--inspect=0.0.0.0:9229", "server/app.js"]
