version: '3.4'

services:
  billingservice:
    image: billingservice
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 202:202
